// Generated by kea-typegen on Sat, 13 Sep 2025 17:11:06 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from './lib/user.api'

export interface authLogicType extends Logic {
    actionCreators: {
        setJwtToken: (jwtToken: string) => ({
            type: "set jwt token (src.authLogic)";
            payload: {
                jwtToken: string;
            };
        });
        setUserData: (userData: User) => ({
            type: "set user data (src.authLogic)";
            payload: {
                userData: User;
            };
        });
        reset: () => ({
            type: "reset (src.authLogic)";
            payload: {
                value: true;
            };
        });
        loadJwtToken: (googleCode: string) => ({
            type: "load jwt token (src.authLogic)";
            payload: string;
        });
        loadJwtTokenSuccess: (jwtToken: string | null, payload?: string) => ({
            type: "load jwt token success (src.authLogic)";
            payload: {
                jwtToken: string | null;
                payload?: string;
            };
        });
        loadJwtTokenFailure: (error: string, errorObject?: any) => ({
            type: "load jwt token failure (src.authLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadUserData: () => ({
            type: "load user data (src.authLogic)";
            payload: any;
        });
        loadUserDataSuccess: (userData: User, payload?: any) => ({
            type: "load user data success (src.authLogic)";
            payload: {
                userData: User;
                payload?: any;
            };
        });
        loadUserDataFailure: (error: string, errorObject?: any) => ({
            type: "load user data failure (src.authLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set jwt token (src.authLogic)": "setJwtToken";
        "set user data (src.authLogic)": "setUserData";
        "reset (src.authLogic)": "reset";
        "load jwt token (src.authLogic)": "loadJwtToken";
        "load jwt token success (src.authLogic)": "loadJwtTokenSuccess";
        "load jwt token failure (src.authLogic)": "loadJwtTokenFailure";
        "load user data (src.authLogic)": "loadUserData";
        "load user data success (src.authLogic)": "loadUserDataSuccess";
        "load user data failure (src.authLogic)": "loadUserDataFailure";
    };
    actionTypes: {
        setJwtToken: "set jwt token (src.authLogic)";
        setUserData: "set user data (src.authLogic)";
        reset: "reset (src.authLogic)";
        loadJwtToken: "load jwt token (src.authLogic)";
        loadJwtTokenSuccess: "load jwt token success (src.authLogic)";
        loadJwtTokenFailure: "load jwt token failure (src.authLogic)";
        loadUserData: "load user data (src.authLogic)";
        loadUserDataSuccess: "load user data success (src.authLogic)";
        loadUserDataFailure: "load user data failure (src.authLogic)";
    };
    actions: {
        setJwtToken: (jwtToken: string) => void;
        setUserData: (userData: User) => void;
        reset: () => void;
        loadJwtToken: (googleCode: string) => void;
        loadJwtTokenSuccess: (jwtToken: string | null, payload?: string) => void;
        loadJwtTokenFailure: (error: string, errorObject?: any) => void;
        loadUserData: () => void;
        loadUserDataSuccess: (userData: User, payload?: any) => void;
        loadUserDataFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setJwtToken: (jwtToken: string) => Promise<any>;
        setUserData: (userData: User) => Promise<any>;
        reset: () => Promise<any>;
        loadJwtToken: (googleCode: string) => Promise<any>;
        loadJwtTokenSuccess: (jwtToken: string | null, payload?: string) => Promise<any>;
        loadJwtTokenFailure: (error: string, errorObject?: any) => Promise<any>;
        loadUserData: () => Promise<any>;
        loadUserDataSuccess: (userData: User, payload?: any) => Promise<any>;
        loadUserDataFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        userData: User | null;
        jwtToken: string | null;
        jwtTokenLoading: boolean;
        userDataLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "authLogic"
    ];
    pathString: "src.authLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        userData: User | null;
        jwtToken: string | null;
        jwtTokenLoading: boolean;
        userDataLoading: boolean;
    };
    reducers: {
        userData: (state: User | null, action: any, fullState: any) => User | null;
        jwtToken: (state: string | null, action: any, fullState: any) => string | null;
        jwtTokenLoading: (state: boolean, action: any, fullState: any) => boolean;
        userDataLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        userData: User | null;
        jwtToken: string | null;
        jwtTokenLoading: boolean;
        userDataLoading: boolean;
    };
    selectors: {
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        jwtTokenLoading: (state: any, props?: any) => boolean;
        userDataLoading: (state: any, props?: any) => boolean;
        isLoggedIn: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        userData: User | null;
        jwtToken: string | null;
        jwtTokenLoading: boolean;
        userDataLoading: boolean;
        isLoggedIn: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        isLoggedIn: (jwtToken: string | null) => boolean;
    };
}