/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMeRouteImport } from './routes/app/me'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppKeysRouteImport } from './routes/app/keys'
import { Route as AppProjectRouteRouteImport } from './routes/app/project/route'
import { Route as AppProjectProjectIdRouteImport } from './routes/app/project/$projectId'
import { Route as AppCallbacksOauthGoogleRouteImport } from './routes/app/callbacks/oauth/google'
import { Route as AppCallbacksOauthGithubRouteImport } from './routes/app/callbacks/oauth/github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/app/me',
  path: '/app/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/app/keys',
  path: '/app/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectRouteRoute = AppProjectRouteRouteImport.update({
  id: '/app/project',
  path: '/app/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectProjectIdRoute = AppProjectProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectRouteRoute,
} as any)
const AppCallbacksOauthGoogleRoute = AppCallbacksOauthGoogleRouteImport.update({
  id: '/app/callbacks/oauth/google',
  path: '/app/callbacks/oauth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallbacksOauthGithubRoute = AppCallbacksOauthGithubRouteImport.update({
  id: '/app/callbacks/oauth/github',
  path: '/app/callbacks/oauth/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/project': typeof AppProjectRouteRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/login': typeof AppLoginRoute
  '/app/me': typeof AppMeRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/project': typeof AppProjectRouteRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/login': typeof AppLoginRoute
  '/app/me': typeof AppMeRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/project': typeof AppProjectRouteRouteWithChildren
  '/app/keys': typeof AppKeysRoute
  '/app/login': typeof AppLoginRoute
  '/app/me': typeof AppMeRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/callbacks/oauth/github': typeof AppCallbacksOauthGithubRoute
  '/app/callbacks/oauth/google': typeof AppCallbacksOauthGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/project'
    | '/app/keys'
    | '/app/login'
    | '/app/me'
    | '/app/project/$projectId'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/project'
    | '/app/keys'
    | '/app/login'
    | '/app/me'
    | '/app/project/$projectId'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  id:
    | '__root__'
    | '/'
    | '/app/project'
    | '/app/keys'
    | '/app/login'
    | '/app/me'
    | '/app/project/$projectId'
    | '/app/callbacks/oauth/github'
    | '/app/callbacks/oauth/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppProjectRouteRoute: typeof AppProjectRouteRouteWithChildren
  AppKeysRoute: typeof AppKeysRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMeRoute: typeof AppMeRoute
  AppCallbacksOauthGithubRoute: typeof AppCallbacksOauthGithubRoute
  AppCallbacksOauthGoogleRoute: typeof AppCallbacksOauthGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/me': {
      id: '/app/me'
      path: '/app/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/app/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project': {
      id: '/app/project'
      path: '/app/project'
      fullPath: '/app/project'
      preLoaderRoute: typeof AppProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project/$projectId': {
      id: '/app/project/$projectId'
      path: '/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteImport
      parentRoute: typeof AppProjectRouteRoute
    }
    '/app/callbacks/oauth/google': {
      id: '/app/callbacks/oauth/google'
      path: '/app/callbacks/oauth/google'
      fullPath: '/app/callbacks/oauth/google'
      preLoaderRoute: typeof AppCallbacksOauthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/callbacks/oauth/github': {
      id: '/app/callbacks/oauth/github'
      path: '/app/callbacks/oauth/github'
      fullPath: '/app/callbacks/oauth/github'
      preLoaderRoute: typeof AppCallbacksOauthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppProjectRouteRouteChildren {
  AppProjectProjectIdRoute: typeof AppProjectProjectIdRoute
}

const AppProjectRouteRouteChildren: AppProjectRouteRouteChildren = {
  AppProjectProjectIdRoute: AppProjectProjectIdRoute,
}

const AppProjectRouteRouteWithChildren = AppProjectRouteRoute._addFileChildren(
  AppProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppProjectRouteRoute: AppProjectRouteRouteWithChildren,
  AppKeysRoute: AppKeysRoute,
  AppLoginRoute: AppLoginRoute,
  AppMeRoute: AppMeRoute,
  AppCallbacksOauthGithubRoute: AppCallbacksOauthGithubRoute,
  AppCallbacksOauthGoogleRoute: AppCallbacksOauthGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
