// Generated by kea-typegen on Sat, 20 Sep 2025 19:29:15 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface commonLogicType extends Logic {
    actionCreators: {
        setInviteIdToShowAfterLogin: (inviteIdToShowAfterLogin: string | null) => ({
            type: "set invite id to show after login (src.lib.logics.commonLogic)";
            payload: {
                inviteIdToShowAfterLogin: string | null;
            };
        });
    };
    actionKeys: {
        "set invite id to show after login (src.lib.logics.commonLogic)": "setInviteIdToShowAfterLogin";
    };
    actionTypes: {
        setInviteIdToShowAfterLogin: "set invite id to show after login (src.lib.logics.commonLogic)";
    };
    actions: {
        setInviteIdToShowAfterLogin: (inviteIdToShowAfterLogin: string | null) => void;
    };
    asyncActions: {
        setInviteIdToShowAfterLogin: (inviteIdToShowAfterLogin: string | null) => Promise<any>;
    };
    defaults: {
        inviteIdToShowAfterLogin: string | null;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "lib",
        "logics",
        "commonLogic"
    ];
    pathString: "src.lib.logics.commonLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        inviteIdToShowAfterLogin: string | null;
    };
    reducers: {
        inviteIdToShowAfterLogin: (state: string | null, action: any, fullState: any) => string | null;
    };
    selector: (state: any) => {
        inviteIdToShowAfterLogin: string | null;
    };
    selectors: {
        inviteIdToShowAfterLogin: (state: any, props?: any) => string | null;
    };
    sharedListeners: {};
    values: {
        inviteIdToShowAfterLogin: string | null;
    };
    _isKea: true;
    _isKeaWithKey: false;
}