// Generated by kea-typegen on Sun, 14 Sep 2025 13:13:51 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../api/user.api'

export interface keyLogicType extends Logic {
    actionCreators: {
        setUserData: (userData: User) => ({
            type: "set user data (src.lib.logics.keyLogic)";
            payload: {
                userData: User;
            };
        });
        setUpPassphrase: (passphrase: string) => ({
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        setPassphrase: (passphrase: string) => ({
            type: "set passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        setLocalEncryptedPrivateKey: (encryptedPrivateKey: string) => ({
            type: "set local encrypted private key (src.lib.logics.keyLogic)";
            payload: {
                encryptedPrivateKey: string;
            };
        });
        decryptPrivateKey: () => ({
            type: "decrypt private key (src.lib.logics.keyLogic)";
            payload: any;
        });
        decryptPrivateKeySuccess: (privateKeyDecrypted: string | null, payload?: any) => ({
            type: "decrypt private key success (src.lib.logics.keyLogic)";
            payload: {
                privateKeyDecrypted: string | null;
                payload?: any;
            };
        });
        decryptPrivateKeyFailure: (error: string, errorObject?: any) => ({
            type: "decrypt private key failure (src.lib.logics.keyLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set user data (src.lib.logics.keyLogic)": "setUserData";
        "set up passphrase (src.lib.logics.keyLogic)": "setUpPassphrase";
        "set passphrase (src.lib.logics.keyLogic)": "setPassphrase";
        "set local encrypted private key (src.lib.logics.keyLogic)": "setLocalEncryptedPrivateKey";
        "decrypt private key (src.lib.logics.keyLogic)": "decryptPrivateKey";
        "decrypt private key success (src.lib.logics.keyLogic)": "decryptPrivateKeySuccess";
        "decrypt private key failure (src.lib.logics.keyLogic)": "decryptPrivateKeyFailure";
    };
    actionTypes: {
        setUserData: "set user data (src.lib.logics.keyLogic)";
        setUpPassphrase: "set up passphrase (src.lib.logics.keyLogic)";
        setPassphrase: "set passphrase (src.lib.logics.keyLogic)";
        setLocalEncryptedPrivateKey: "set local encrypted private key (src.lib.logics.keyLogic)";
        decryptPrivateKey: "decrypt private key (src.lib.logics.keyLogic)";
        decryptPrivateKeySuccess: "decrypt private key success (src.lib.logics.keyLogic)";
        decryptPrivateKeyFailure: "decrypt private key failure (src.lib.logics.keyLogic)";
    };
    actions: {
        setUserData: (userData: User) => void;
        setUpPassphrase: (passphrase: string) => void;
        setPassphrase: (passphrase: string) => void;
        setLocalEncryptedPrivateKey: (encryptedPrivateKey: string) => void;
        decryptPrivateKey: () => void;
        decryptPrivateKeySuccess: (privateKeyDecrypted: string | null, payload?: any) => void;
        decryptPrivateKeyFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setUserData: (userData: User) => Promise<any>;
        setUpPassphrase: (passphrase: string) => Promise<any>;
        setPassphrase: (passphrase: string) => Promise<any>;
        setLocalEncryptedPrivateKey: (encryptedPrivateKey: string) => Promise<any>;
        decryptPrivateKey: () => Promise<any>;
        decryptPrivateKeySuccess: (privateKeyDecrypted: string | null, payload?: any) => Promise<any>;
        decryptPrivateKeyFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        passphrase: string | null;
        localEncryptedPrivateKey: string | null;
        privateKeyDecrypted: any;
        privateKeyDecryptedLoading: boolean;
    };
    events: {};
    key: undefined;
    listeners: {
        "setUpPassphrase": ((action: {
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "keyLogic"
    ];
    pathString: "src.lib.logics.keyLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        passphrase: string | null;
        localEncryptedPrivateKey: string | null;
        privateKeyDecrypted: any;
        privateKeyDecryptedLoading: boolean;
    };
    reducers: {
        passphrase: (state: string | null, action: any, fullState: any) => string | null;
        localEncryptedPrivateKey: (state: string | null, action: any, fullState: any) => string | null;
        privateKeyDecrypted: (state: any, action: any, fullState: any) => any;
        privateKeyDecryptedLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        passphrase: string | null;
        localEncryptedPrivateKey: string | null;
        privateKeyDecrypted: any;
        privateKeyDecryptedLoading: boolean;
    };
    selectors: {
        passphrase: (state: any, props?: any) => string | null;
        localEncryptedPrivateKey: (state: any, props?: any) => string | null;
        privateKeyDecrypted: (state: any, props?: any) => any;
        privateKeyDecryptedLoading: (state: any, props?: any) => boolean;
        userData: (state: any, props?: any) => User | null;
        shouldSetUpPassphrase: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        passphrase: string | null;
        localEncryptedPrivateKey: string | null;
        privateKeyDecrypted: any;
        privateKeyDecryptedLoading: boolean;
        userData: User | null;
        shouldSetUpPassphrase: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        shouldSetUpPassphrase: (userData: User | null) => boolean;
    };
}