// Generated by kea-typegen on Sun, 28 Sep 2025 18:14:20 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { User } from '../api/user.api'

export interface keyLogicType extends Logic {
    actionCreators: {
        loadUserData: () => ({
            type: "load user data (src.lib.logics.keyLogic)";
            payload: any;
        });
        setPassphrase: (passphrase: string) => ({
            type: "set passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        setPrivateKeyDecrypted: (privateKeyDecrypted: string | null) => ({
            type: "set private key decrypted (src.lib.logics.keyLogic)";
            payload: {
                privateKeyDecrypted: string | null;
            };
        });
        setUpPassphrase: (passphrase: string) => ({
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        });
        decryptPrivateKey: () => ({
            type: "decrypt private key (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        });
    };
    actionKeys: {
        "load user data (src.lib.logics.keyLogic)": "loadUserData";
        "set passphrase (src.lib.logics.keyLogic)": "setPassphrase";
        "set private key decrypted (src.lib.logics.keyLogic)": "setPrivateKeyDecrypted";
        "set up passphrase (src.lib.logics.keyLogic)": "setUpPassphrase";
        "decrypt private key (src.lib.logics.keyLogic)": "decryptPrivateKey";
    };
    actionTypes: {
        loadUserData: "load user data (src.lib.logics.keyLogic)";
        setPassphrase: "set passphrase (src.lib.logics.keyLogic)";
        setPrivateKeyDecrypted: "set private key decrypted (src.lib.logics.keyLogic)";
        setUpPassphrase: "set up passphrase (src.lib.logics.keyLogic)";
        decryptPrivateKey: "decrypt private key (src.lib.logics.keyLogic)";
    };
    actions: {
        loadUserData: () => void;
        setPassphrase: (passphrase: string) => void;
        setPrivateKeyDecrypted: (privateKeyDecrypted: string | null) => void;
        setUpPassphrase: (passphrase: string) => void;
        decryptPrivateKey: () => void;
    };
    asyncActions: {
        loadUserData: () => Promise<any>;
        setPassphrase: (passphrase: string) => Promise<any>;
        setPrivateKeyDecrypted: (privateKeyDecrypted: string | null) => Promise<any>;
        setUpPassphrase: (passphrase: string) => Promise<any>;
        decryptPrivateKey: () => Promise<any>;
    };
    defaults: {
        passphrase: string | null;
        privateKeyDecrypted: string | null;
    };
    events: {};
    key: undefined;
    listeners: {
        "setUpPassphrase": ((action: {
            type: "set up passphrase (src.lib.logics.keyLogic)";
            payload: {
                passphrase: string;
            };
        }, previousState: any) => void | Promise<void>)[];
        "decryptPrivateKey": ((action: {
            type: "decrypt private key (src.lib.logics.keyLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "keyLogic"
    ];
    pathString: "src.lib.logics.keyLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        passphrase: string | null;
        privateKeyDecrypted: string | null;
    };
    reducers: {
        passphrase: (state: string | null, action: any, fullState: any) => string | null;
        privateKeyDecrypted: (state: string | null, action: any, fullState: any) => string | null;
    };
    selector: (state: any) => {
        passphrase: string | null;
        privateKeyDecrypted: string | null;
    };
    selectors: {
        passphrase: (state: any, props?: any) => string | null;
        privateKeyDecrypted: (state: any, props?: any) => string | null;
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        shouldSetUpPassphrase: (state: any, props?: any) => boolean;
        browserIsUnlocked: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        passphrase: string | null;
        privateKeyDecrypted: string | null;
        userData: User | null;
        jwtToken: string | null;
        shouldSetUpPassphrase: boolean;
        browserIsUnlocked: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        shouldSetUpPassphrase: (userData: User | null) => boolean;
        browserIsUnlocked: (privateKeyDecrypted: string | null) => boolean;
    };
}