// Generated by kea-typegen on Mon, 22 Sep 2025 21:04:40 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DecryptedProject, ProjectLogicProps } from './projectLogic'
import type { User } from '../api/user.api'
import type { Project, ProjectMember } from '../api/projects.api'

export interface projectLogicType extends Logic {
    actionCreators: {
        updateProjectContent: () => ({
            type: "update project content (src.lib.logics.projectLogic)";
            payload: {
                value: true;
            };
        });
        toggleHistoryView: () => ({
            type: "toggle history view (src.lib.logics.projectLogic)";
            payload: {
                value: true;
            };
        });
        setIsShowingHistory: (isShowingHistory: boolean) => ({
            type: "set is showing history (src.lib.logics.projectLogic)";
            payload: {
                isShowingHistory: boolean;
            };
        });
        selectHistoryChange: (changeId: string | null, patch: string | null) => ({
            type: "select history change (src.lib.logics.projectLogic)";
            payload: {
                changeId: string | null;
                patch: string | null;
            };
        });
        setPatches: (patches: string[]) => ({
            type: "set patches (src.lib.logics.projectLogic)";
            payload: {
                patches: string[];
            };
        });
        computePatches: (versions: string[]) => ({
            type: "compute patches (src.lib.logics.projectLogic)";
            payload: {
                versions: string[];
            };
        });
        setInputValue: (content: string) => ({
            type: "set input value (src.lib.logics.projectLogic)";
            payload: {
                content: string;
            };
        });
        setIsSubmitting: (isSubmitting: boolean) => ({
            type: "set is submitting (src.lib.logics.projectLogic)";
            payload: {
                isSubmitting: boolean;
            };
        });
        loadProjectData: () => ({
            type: "load project data (src.lib.logics.projectLogic)";
            payload: any;
        });
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => ({
            type: "load project data success (src.lib.logics.projectLogic)";
            payload: {
                projectData: {
                    content: string;
                    id: string;
                    members: ProjectMember[];
                    name: string;
                    passphraseAsKey: string;
                    updatedAt: string;
                };
                payload?: any;
            };
        });
        loadProjectDataFailure: (error: string, errorObject?: any) => ({
            type: "load project data failure (src.lib.logics.projectLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadProjectVersions: () => ({
            type: "load project versions (src.lib.logics.projectLogic)";
            payload: any;
        });
        loadProjectVersionsSuccess: (projectVersions: string[], payload?: any) => ({
            type: "load project versions success (src.lib.logics.projectLogic)";
            payload: {
                projectVersions: string[];
                payload?: any;
            };
        });
        loadProjectVersionsFailure: (error: string, errorObject?: any) => ({
            type: "load project versions failure (src.lib.logics.projectLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "update project content (src.lib.logics.projectLogic)": "updateProjectContent";
        "toggle history view (src.lib.logics.projectLogic)": "toggleHistoryView";
        "set is showing history (src.lib.logics.projectLogic)": "setIsShowingHistory";
        "select history change (src.lib.logics.projectLogic)": "selectHistoryChange";
        "set patches (src.lib.logics.projectLogic)": "setPatches";
        "compute patches (src.lib.logics.projectLogic)": "computePatches";
        "set input value (src.lib.logics.projectLogic)": "setInputValue";
        "set is submitting (src.lib.logics.projectLogic)": "setIsSubmitting";
        "load project data (src.lib.logics.projectLogic)": "loadProjectData";
        "load project data success (src.lib.logics.projectLogic)": "loadProjectDataSuccess";
        "load project data failure (src.lib.logics.projectLogic)": "loadProjectDataFailure";
        "load project versions (src.lib.logics.projectLogic)": "loadProjectVersions";
        "load project versions success (src.lib.logics.projectLogic)": "loadProjectVersionsSuccess";
        "load project versions failure (src.lib.logics.projectLogic)": "loadProjectVersionsFailure";
    };
    actionTypes: {
        updateProjectContent: "update project content (src.lib.logics.projectLogic)";
        toggleHistoryView: "toggle history view (src.lib.logics.projectLogic)";
        setIsShowingHistory: "set is showing history (src.lib.logics.projectLogic)";
        selectHistoryChange: "select history change (src.lib.logics.projectLogic)";
        setPatches: "set patches (src.lib.logics.projectLogic)";
        computePatches: "compute patches (src.lib.logics.projectLogic)";
        setInputValue: "set input value (src.lib.logics.projectLogic)";
        setIsSubmitting: "set is submitting (src.lib.logics.projectLogic)";
        loadProjectData: "load project data (src.lib.logics.projectLogic)";
        loadProjectDataSuccess: "load project data success (src.lib.logics.projectLogic)";
        loadProjectDataFailure: "load project data failure (src.lib.logics.projectLogic)";
        loadProjectVersions: "load project versions (src.lib.logics.projectLogic)";
        loadProjectVersionsSuccess: "load project versions success (src.lib.logics.projectLogic)";
        loadProjectVersionsFailure: "load project versions failure (src.lib.logics.projectLogic)";
    };
    actions: {
        updateProjectContent: () => void;
        toggleHistoryView: () => void;
        setIsShowingHistory: (isShowingHistory: boolean) => void;
        selectHistoryChange: (changeId: string | null, patch: string | null) => void;
        setPatches: (patches: string[]) => void;
        computePatches: (versions: string[]) => void;
        setInputValue: (content: string) => void;
        setIsSubmitting: (isSubmitting: boolean) => void;
        loadProjectData: () => void;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => void;
        loadProjectDataFailure: (error: string, errorObject?: any) => void;
        loadProjectVersions: () => void;
        loadProjectVersionsSuccess: (projectVersions: string[], payload?: any) => void;
        loadProjectVersionsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        updateProjectContent: () => Promise<any>;
        toggleHistoryView: () => Promise<any>;
        setIsShowingHistory: (isShowingHistory: boolean) => Promise<any>;
        selectHistoryChange: (changeId: string | null, patch: string | null) => Promise<any>;
        setPatches: (patches: string[]) => Promise<any>;
        computePatches: (versions: string[]) => Promise<any>;
        setInputValue: (content: string) => Promise<any>;
        setIsSubmitting: (isSubmitting: boolean) => Promise<any>;
        loadProjectData: () => Promise<any>;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => Promise<any>;
        loadProjectDataFailure: (error: string, errorObject?: any) => Promise<any>;
        loadProjectVersions: () => Promise<any>;
        loadProjectVersionsSuccess: (projectVersions: string[], payload?: any) => Promise<any>;
        loadProjectVersionsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        selectedHistoryChangeId: string | null;
        patches: string[];
        inputValue: string;
        isSubmitting: boolean;
        projectData: DecryptedProject | null;
        isShowingHistory: boolean;
        projectDataLoading: boolean;
        projectVersions: string[];
        projectVersionsLoading: boolean;
    };
    events: {};
    key: string;
    listeners: {
        "updateProjectContent": ((action: {
            type: "update project content (src.lib.logics.projectLogic)";
            payload: {
                value: true;
            };
        }, previousState: any) => void | Promise<void>)[];
        "computePatches": ((action: {
            type: "compute patches (src.lib.logics.projectLogic)";
            payload: {
                versions: string[];
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "projectLogic"
    ];
    pathString: "src.lib.logics.projectLogic";
    props: ProjectLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        selectedHistoryChangeId: string | null;
        patches: string[];
        inputValue: string;
        isSubmitting: boolean;
        projectData: DecryptedProject | null;
        isShowingHistory: boolean;
        projectDataLoading: boolean;
        projectVersions: string[];
        projectVersionsLoading: boolean;
    };
    reducers: {
        selectedHistoryChangeId: (state: string | null, action: any, fullState: any) => string | null;
        patches: (state: string[], action: any, fullState: any) => string[];
        inputValue: (state: string, action: any, fullState: any) => string;
        isSubmitting: (state: boolean, action: any, fullState: any) => boolean;
        projectData: (state: DecryptedProject | null, action: any, fullState: any) => DecryptedProject | null;
        isShowingHistory: (state: boolean, action: any, fullState: any) => boolean;
        projectDataLoading: (state: boolean, action: any, fullState: any) => boolean;
        projectVersions: (state: string[], action: any, fullState: any) => string[];
        projectVersionsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        selectedHistoryChangeId: string | null;
        patches: string[];
        inputValue: string;
        isSubmitting: boolean;
        projectData: DecryptedProject | null;
        isShowingHistory: boolean;
        projectDataLoading: boolean;
        projectVersions: string[];
        projectVersionsLoading: boolean;
    };
    selectors: {
        selectedHistoryChangeId: (state: any, props?: any) => string | null;
        patches: (state: any, props?: any) => string[];
        inputValue: (state: any, props?: any) => string;
        isSubmitting: (state: any, props?: any) => boolean;
        projectData: (state: any, props?: any) => DecryptedProject | null;
        isShowingHistory: (state: any, props?: any) => boolean;
        projectDataLoading: (state: any, props?: any) => boolean;
        projectVersions: (state: any, props?: any) => string[];
        projectVersionsLoading: (state: any, props?: any) => boolean;
        privateKeyDecrypted: (state: any, props?: any) => string | null;
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        projects: (state: any, props?: any) => Project[];
        isEditorDirty: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        selectedHistoryChangeId: string | null;
        patches: string[];
        inputValue: string;
        isSubmitting: boolean;
        projectData: DecryptedProject | null;
        isShowingHistory: boolean;
        projectDataLoading: boolean;
        projectVersions: string[];
        projectVersionsLoading: boolean;
        privateKeyDecrypted: string | null;
        userData: User | null;
        jwtToken: string | null;
        projects: Project[];
        isEditorDirty: boolean;
    };
    _isKea: true;
    _isKeaWithKey: true;
    __keaTypeGenInternalSelectorTypes: {
        isEditorDirty: (inputValue: string, projectData: DecryptedProject | null) => boolean;
    };
}