// Generated by kea-typegen on Thu, 18 Sep 2025 19:11:06 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DecryptedProject, ProjectLogicProps } from './projectLogic'
import type { User } from '../api/user.api'
import type { Project } from '../api/projects.api'

export interface projectLogicType extends Logic {
    actionCreators: {
        updateProjectContent: (content: string) => ({
            type: "update project content (src.lib.logics.projectLogic)";
            payload: {
                content: string;
            };
        });
        toggleHistoryView: () => ({
            type: "toggle history view (src.lib.logics.projectLogic)";
            payload: {
                value: true;
            };
        });
        loadProjectData: () => ({
            type: "load project data (src.lib.logics.projectLogic)";
            payload: any;
        });
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            name: string;
            passphraseAsKey: string;
        }, payload?: any) => ({
            type: "load project data success (src.lib.logics.projectLogic)";
            payload: {
                projectData: {
                    content: string;
                    id: string;
                    name: string;
                    passphraseAsKey: string;
                };
                payload?: any;
            };
        });
        loadProjectDataFailure: (error: string, errorObject?: any) => ({
            type: "load project data failure (src.lib.logics.projectLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "update project content (src.lib.logics.projectLogic)": "updateProjectContent";
        "toggle history view (src.lib.logics.projectLogic)": "toggleHistoryView";
        "load project data (src.lib.logics.projectLogic)": "loadProjectData";
        "load project data success (src.lib.logics.projectLogic)": "loadProjectDataSuccess";
        "load project data failure (src.lib.logics.projectLogic)": "loadProjectDataFailure";
    };
    actionTypes: {
        updateProjectContent: "update project content (src.lib.logics.projectLogic)";
        toggleHistoryView: "toggle history view (src.lib.logics.projectLogic)";
        loadProjectData: "load project data (src.lib.logics.projectLogic)";
        loadProjectDataSuccess: "load project data success (src.lib.logics.projectLogic)";
        loadProjectDataFailure: "load project data failure (src.lib.logics.projectLogic)";
    };
    actions: {
        updateProjectContent: (content: string) => void;
        toggleHistoryView: () => void;
        loadProjectData: () => void;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            name: string;
            passphraseAsKey: string;
        }, payload?: any) => void;
        loadProjectDataFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        updateProjectContent: (content: string) => Promise<any>;
        toggleHistoryView: () => Promise<any>;
        loadProjectData: () => Promise<any>;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            name: string;
            passphraseAsKey: string;
        }, payload?: any) => Promise<any>;
        loadProjectDataFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        isShowingHistory: boolean;
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
    };
    events: {};
    key: string;
    listeners: {
        "updateProjectContent": ((action: {
            type: "update project content (src.lib.logics.projectLogic)";
            payload: {
                content: string;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "projectLogic"
    ];
    pathString: "src.lib.logics.projectLogic";
    props: ProjectLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        isShowingHistory: boolean;
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
    };
    reducers: {
        isShowingHistory: (state: boolean, action: any, fullState: any) => boolean;
        projectData: (state: DecryptedProject | null, action: any, fullState: any) => DecryptedProject | null;
        projectDataLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        isShowingHistory: boolean;
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
    };
    selectors: {
        isShowingHistory: (state: any, props?: any) => boolean;
        projectData: (state: any, props?: any) => DecryptedProject | null;
        projectDataLoading: (state: any, props?: any) => boolean;
        privateKeyDecrypted: (state: any, props?: any) => string | null;
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        projects: (state: any, props?: any) => Project[];
    };
    sharedListeners: {};
    values: {
        isShowingHistory: boolean;
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
        privateKeyDecrypted: string | null;
        userData: User | null;
        jwtToken: string | null;
        projects: Project[];
    };
    _isKea: true;
    _isKeaWithKey: true;
}