// Generated by kea-typegen on Fri, 26 Sep 2025 15:29:27 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { DecryptedProject, Patch, ProjectDataLogicProps } from './projectDataLogic'
import type { User } from '../api/user.api'
import type { DecryptedVersion, Integrations, Project, ProjectMember, ProjectMemberRole } from '../api/projects.api'

export interface projectDataLogicType extends Logic {
    actionCreators: {
        setPatches: (patches: Patch[]) => ({
            type: "set patches (src.lib.logics.projectDataLogic)";
            payload: {
                patches: Patch[];
            };
        });
        computePatches: (versions: DecryptedVersion[]) => ({
            type: "compute patches (src.lib.logics.projectDataLogic)";
            payload: {
                versions: DecryptedVersion[];
            };
        });
        loadProjectData: () => ({
            type: "load project data (src.lib.logics.projectDataLogic)";
            payload: any;
        });
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            integrations: Integrations;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => ({
            type: "load project data success (src.lib.logics.projectDataLogic)";
            payload: {
                projectData: {
                    content: string;
                    id: string;
                    integrations: Integrations;
                    members: ProjectMember[];
                    name: string;
                    passphraseAsKey: string;
                    updatedAt: string;
                };
                payload?: any;
            };
        });
        loadProjectDataFailure: (error: string, errorObject?: any) => ({
            type: "load project data failure (src.lib.logics.projectDataLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        loadProjectVersions: () => ({
            type: "load project versions (src.lib.logics.projectDataLogic)";
            payload: any;
        });
        loadProjectVersionsSuccess: (projectVersions: DecryptedVersion[], payload?: any) => ({
            type: "load project versions success (src.lib.logics.projectDataLogic)";
            payload: {
                projectVersions: DecryptedVersion[];
                payload?: any;
            };
        });
        loadProjectVersionsFailure: (error: string, errorObject?: any) => ({
            type: "load project versions failure (src.lib.logics.projectDataLogic)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set patches (src.lib.logics.projectDataLogic)": "setPatches";
        "compute patches (src.lib.logics.projectDataLogic)": "computePatches";
        "load project data (src.lib.logics.projectDataLogic)": "loadProjectData";
        "load project data success (src.lib.logics.projectDataLogic)": "loadProjectDataSuccess";
        "load project data failure (src.lib.logics.projectDataLogic)": "loadProjectDataFailure";
        "load project versions (src.lib.logics.projectDataLogic)": "loadProjectVersions";
        "load project versions success (src.lib.logics.projectDataLogic)": "loadProjectVersionsSuccess";
        "load project versions failure (src.lib.logics.projectDataLogic)": "loadProjectVersionsFailure";
    };
    actionTypes: {
        setPatches: "set patches (src.lib.logics.projectDataLogic)";
        computePatches: "compute patches (src.lib.logics.projectDataLogic)";
        loadProjectData: "load project data (src.lib.logics.projectDataLogic)";
        loadProjectDataSuccess: "load project data success (src.lib.logics.projectDataLogic)";
        loadProjectDataFailure: "load project data failure (src.lib.logics.projectDataLogic)";
        loadProjectVersions: "load project versions (src.lib.logics.projectDataLogic)";
        loadProjectVersionsSuccess: "load project versions success (src.lib.logics.projectDataLogic)";
        loadProjectVersionsFailure: "load project versions failure (src.lib.logics.projectDataLogic)";
    };
    actions: {
        setPatches: (patches: Patch[]) => void;
        computePatches: (versions: DecryptedVersion[]) => void;
        loadProjectData: () => void;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            integrations: Integrations;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => void;
        loadProjectDataFailure: (error: string, errorObject?: any) => void;
        loadProjectVersions: () => void;
        loadProjectVersionsSuccess: (projectVersions: DecryptedVersion[], payload?: any) => void;
        loadProjectVersionsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setPatches: (patches: Patch[]) => Promise<any>;
        computePatches: (versions: DecryptedVersion[]) => Promise<any>;
        loadProjectData: () => Promise<any>;
        loadProjectDataSuccess: (projectData: {
            content: string;
            id: string;
            integrations: Integrations;
            members: ProjectMember[];
            name: string;
            passphraseAsKey: string;
            updatedAt: string;
        }, payload?: any) => Promise<any>;
        loadProjectDataFailure: (error: string, errorObject?: any) => Promise<any>;
        loadProjectVersions: () => Promise<any>;
        loadProjectVersionsSuccess: (projectVersions: DecryptedVersion[], payload?: any) => Promise<any>;
        loadProjectVersionsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        patches: Patch[];
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
        projectVersions: DecryptedVersion[];
        projectVersionsLoading: boolean;
    };
    events: {};
    key: string;
    listeners: {
        "computePatches": ((action: {
            type: "compute patches (src.lib.logics.projectDataLogic)";
            payload: {
                versions: DecryptedVersion[];
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "src",
        "lib",
        "logics",
        "projectDataLogic"
    ];
    pathString: "src.lib.logics.projectDataLogic";
    props: ProjectDataLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        patches: Patch[];
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
        projectVersions: DecryptedVersion[];
        projectVersionsLoading: boolean;
    };
    reducers: {
        patches: (state: Patch[], action: any, fullState: any) => Patch[];
        projectData: (state: DecryptedProject | null, action: any, fullState: any) => DecryptedProject | null;
        projectDataLoading: (state: boolean, action: any, fullState: any) => boolean;
        projectVersions: (state: DecryptedVersion[], action: any, fullState: any) => DecryptedVersion[];
        projectVersionsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        patches: Patch[];
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
        projectVersions: DecryptedVersion[];
        projectVersionsLoading: boolean;
    };
    selectors: {
        patches: (state: any, props?: any) => Patch[];
        projectData: (state: any, props?: any) => DecryptedProject | null;
        projectDataLoading: (state: any, props?: any) => boolean;
        projectVersions: (state: any, props?: any) => DecryptedVersion[];
        projectVersionsLoading: (state: any, props?: any) => boolean;
        privateKeyDecrypted: (state: any, props?: any) => string | null;
        userData: (state: any, props?: any) => User | null;
        jwtToken: (state: any, props?: any) => string | null;
        projects: (state: any, props?: any) => Project[];
        lastEditAuthor: (state: any, props?: any) => ProjectMember;
        currentUserRole: (state: any, props?: any) => ProjectMemberRole | undefined;
    };
    sharedListeners: {};
    values: {
        patches: Patch[];
        projectData: DecryptedProject | null;
        projectDataLoading: boolean;
        projectVersions: DecryptedVersion[];
        projectVersionsLoading: boolean;
        privateKeyDecrypted: string | null;
        userData: User | null;
        jwtToken: string | null;
        projects: Project[];
        lastEditAuthor: ProjectMember;
        currentUserRole: ProjectMemberRole | undefined;
    };
    _isKea: true;
    _isKeaWithKey: true;
    __keaTypeGenInternalSelectorTypes: {
        lastEditAuthor: (patches: Patch[]) => ProjectMember;
        currentUserRole: (projectData: DecryptedProject | null) => ProjectMemberRole | undefined;
    };
}